version: '3.8'

services:
  rabbitmq1:
    image: rabbitmq:3.8-management
    hostname: rabbitmq1
    container_name: rabbitmq1
    environment:
      RABBITMQ_ERLANG_COOKIE: 'secretcookie'
      RABBITMQ_NODENAME: 'rabbit@rabbitmq1'
      RABBITMQ_DEFAULT_USER: 'guest'
      RABBITMQ_DEFAULT_PASS: 'guest'
      RABBITMQ_DEFAULT_VHOST: '/'
    networks:
      rabbitmq_network:
        aliases:
          - rabbitmq.test
    ports:
      - "15672:15672"
      - "5672:5672" # Main RabbitMQ port
    volumes:
      - ./cluster-entrypoint.sh:/usr/local/bin/cluster-entrypoint.sh
    entrypoint: /usr/local/bin/cluster-entrypoint.sh

  rabbitmq2:
    image: rabbitmq:3.8-management
    hostname: rabbitmq2
    container_name: rabbitmq2
    environment:
      RABBITMQ_ERLANG_COOKIE: 'secretcookie'
      RABBITMQ_NODENAME: 'rabbit@rabbitmq2'
      JOIN_CLUSTER_HOST: 'rabbitmq1'
    depends_on:
      - rabbitmq1
    networks:
      rabbitmq_network:
        aliases:
          - rabbitmq.test
    ports:
      - "15673:15672"
      - "5673:5672" # Main RabbitMQ port
    volumes:
      - ./cluster-entrypoint.sh:/usr/local/bin/cluster-entrypoint.sh
    entrypoint: /usr/local/bin/cluster-entrypoint.sh

  rabbitmq3:
    image: rabbitmq:3.8-management
    hostname: rabbitmq3
    container_name: rabbitmq3
    environment:
      RABBITMQ_ERLANG_COOKIE: 'secretcookie'
      RABBITMQ_NODENAME: 'rabbit@rabbitmq3'
      JOIN_CLUSTER_HOST: 'rabbitmq1'
    depends_on:
      - rabbitmq1
      - rabbitmq2
    networks:
      rabbitmq_network:
        aliases:
          - rabbitmq.test
    ports:
      - "15674:15672"
      - "5674:5672" # Main RabbitMQ port
    volumes:
      - ./cluster-entrypoint.sh:/usr/local/bin/cluster-entrypoint.sh
    entrypoint: /usr/local/bin/cluster-entrypoint.sh

networks:
  rabbitmq_network:
    driver: bridge
